### ISSUE TITLE
Doubt in training the data...

### ISSUE THREAD

**Issue by gangubai** [AntiAegis/Face-Attendance-System#5]
Hello ..I am currently second year student in IIT Bombay..I am individually working on the same project .
I did go through your repo..I do have doubt in the training process..How can I make my own class folder of data in which I have to enter at least 50 images of each ID? Like exactly the location??
So can you please give more brief info for training process with proper locations ??
Thanks in advance!!

**Comment by thuyngch** [comment]
Hi @gangubai,
I think a video to introduce the training process may be easier for people to use the repository.
So, in 2-3 days, my team will make that video.

**Comment by AntiAegis** [comment]
#6

**Comment by AntiAegis** [comment]
#6

**Comment by thuyngch** [comment]
#6 Doubt in training the model

**Comment by dotieuthien** [comment]
This is demo video for your question.
https://www.youtube.com/watch?v=vd7j1YvqslY&t=104s

**Comment by gangubai** [comment]
Thanks for the video!!
But still facing the error as follow:

(attendance) aam@A-Inspiron-3542:~/A_Projects/Face-Attendance-System-master/apis$ python 4.train.py 
Traceback (most recent call last):
  File "4.train.py", line 8, in <module>
    import li.detect_face as detect_face
  File "/home/A_Projects/Face-Attendance-System-master/apis/li/detect_face.py", line 34, in <module>
    import cv2
ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /home/ankitakulkarni/anaconda3/envs/attendance/lib/python3.5/site-packages/../../libopencv_objdetect.so.3.4)

**Comment by gangubai** [comment]
Thanks for the video!!!
But facing the error as follows:

(attendance) anm@Anm-Inspiron-3542:~/A_Projects/Face-Attendance-System-master/apis$ python 4.train.py 
Traceback (most recent call last):
  File "4.train.py", line 8, in <module>
    import li.detect_face as detect_face
  File "/home/anm/A_Projects/Face-Attendance-System-master/apis/li/detect_face.py", line 34, in <module>
    import cv2
ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /home/anm/anaconda3/envs/attendance/lib/python3.5/site-packages/../../libopencv_objdetect.so.3.4)

**Comment by thuyngch** [comment]
@gangubai This error is due to our installation of opencv package.
The opencv requires GLIBCXX_3.4.22 library but your computer does not have this library.
How did you install opencv?

**Comment by gangubai** [comment]
sudo apt-get install python-opencv  ......I used this command while creating the environment for the project...
But it works fine for other environments...Is this wrong??
what is right command then?

Thanks!

**Comment by thuyngch** [comment]
I suggest you can try this snippet of code to install opencv:
`workon attendance`
`pip install opencv-python==3.3.1.11`

**Comment by gangubai** [comment]
Thanks it works fine!!!
Now again got the error:


attendance-System-master/apis$ python 4.train.py 
Training classifier...
Traceback (most recent call last):
  File "4.train.py", line 171, in <module>
    classifier.train_SVM(train_embs, train_labels, valid_embs, valid_labels, path_SVM)
  File "4.train.py", line 76, in train_SVM
    model.fit(embs_train, labels_train)
  File "/home/anm/.local/lib/python3.5/site-packages/sklearn/svm/base.py", line 150, in fit
    y = self._validate_targets(y)
  File "/home/anm/.local/lib/python3.5/site-packages/sklearn/svm/base.py", line 525, in _validate_targets
    " class" % len(cls))
ValueError: The number of classes has to be greater than one; got 1 class

**Comment by thuyngch** [comment]
How many people whom you collected images of their faces? 
I guess that you just did with one person.
Actually, the SVM classifier works with no smaller than two classes. It means you need to collect data from two people or more.

**Comment by gangubai** [comment]
I know that thing...That's why I started with two classes of people first..

**Comment by dotieuthien** [comment]
I think that this error came from your labels (IDs) of two classes which have to different from each other. Thus, could you check it?

**Comment by gangubai** [comment]
Yes I gave them as 3248,3169,3634 like this..In them individually images as 3248_1,3169_1,3169_2 like that manner....

**Comment by dotieuthien** [comment]
Can you print your labels when you run 4.train.py and show me the result?

**Comment by gangubai** [comment]
Attendance-System-master/apis$ python 4.train.py 
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
Training classifier...
Traceback (most recent call last):
  File "4.train.py", line 168, in <module>
    classifier.train_SVM(train_embs, train_labels, valid_embs, valid_labels, path_SVM)
  File "4.train.py", line 71, in train_SVM
    model.fit(embs_train, labels_train)
  File "/home/anm/.local/lib/python3.5/site-packages/sklearn/svm/base.py", line 150, in fit
    y = self._validate_targets(y)
  File "/home/anm/.local/lib/python3.5/site-packages/sklearn/svm/base.py", line 525, in _validate_targets
    " class" % len(cls))
ValueError: The number of classes has to be greater than one; got 1 class

I am giving the proper paths where they are required...But still means it's not getting any classes and corresponding labels as it is printing 0 while I am printing labels..

**Comment by dotieuthien** [comment]
I have already checked and my label is [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 11 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]. I think your path_train_data is issue, my path_train_data = "dataset/train", path_valid_data = "dataset/valid" , path_test_data = "dataset/test", that cover all folder of identities as the root of dataset tree

**Comment by dotieuthien** [comment]
![screenshot from 2019-01-15 10-27-58](https://user-images.githubusercontent.com/30580619/51156975-81a69700-18b0-11e9-91a4-1925dd71cc46.png)
![screenshot from 2019-01-15 10-28-17](https://user-images.githubusercontent.com/30580619/51156979-88cda500-18b0-11e9-84d6-2e1754e1b284.png)

**Comment by gangubai** [comment]
All the paths that are giving from config.py file are correct..But one thing that I found that in features folder only valid.mat is present and not other two test.mat and train.mat and hence that's why it's not getting proper labels and corresponding class.And even it's not created while creating the new dataset..I think this might be the issue ...

![screenshot from 2019-01-15 17-24-16](https://user-images.githubusercontent.com/40833513/51179016-60629c80-18ea-11e9-9eef-30fd11377e7b.png)

**Comment by dotieuthien** [comment]
Ya, that is very reason why you cannot train. However, I have already checked this file which have no error. In your image, file 4.train.py just extract valid.mat that is also the third file, so that mean you cannot run from  line 142 to 155. Can you check it?

**Comment by gangubai** [comment]
Yes..I checked it...Cannot able to run that snippet of code from line 142 to 155..Any solution for this??

Thanks!

**Comment by dotieuthien** [comment]
Because I don't suffer from this problem, you can replace the order of creating mat files to create train.mat. Unless you face with above error (label 0), you can test the next step by print variables related code from 142 to 155

**Comment by gangubai** [comment]
Still facing the same error even after doing the changes..

**Comment by yahyamhi** [comment]
> Still facing the same error even after doing the changes..

Any working solutions to this problem? Thank You
