### ISSUE TITLE
Doubt in training the model

### ISSUE THREAD

**Issue by sonu54321** [AntiAegis/Face-Attendance-System#6]
Hello ..I am computer engineering student ..and I am working on the same project for learning purpose .
I have doubt in the training process..where should I create the dataset for each id for training ? like exactly what location images should be stored?
So can you please give more brief info for training process with proper locations ??
also if possible please share the video showing how to train the model ?
thanks!!!!!!!!!!!!!

**Comment by thuyngch** [comment]
Hi @sonu54321, 
Thanks for your interest in our project.
We will upload a video to guide people on how to train the network soon.

**Comment by dotieuthien** [comment]
This is demo video for your question. 
https://www.youtube.com/watch?v=vd7j1YvqslY&t=104s
