### ISSUE TITLE
Excel Sheet Formats

### ISSUE THREAD

**Issue by bhargavravat** [AntiAegis/Face-Attendance-System#7]
I have installed all the dependencies and with custom dataset and now trying to run camera.py file . 
However it is throwing "Please Open Excels Files" . 

How to proceed ahead in this case ?
![Screenshot from 2019-03-26 16-07-16](https://user-images.githubusercontent.com/11025174/54990656-44156700-4fe1-11e9-837a-05ae95c93fbc.png)

**Comment by thuyngch** [comment]
@RykerLe

**Comment by phuonglvh** [comment]
Hi @bhargavravat, thank you for your interest in our project. There is something wrong in your Application GUI, a **File** button designated to located in the top left corner was missing. 

Here is the right GUI:
![image](https://user-images.githubusercontent.com/30889332/55005278-4641ea80-500e-11e9-8c72-c39962d33850.png) 

I do not know the reason why it is missing, we are under intensive discussion on this issue. You may try  running this application on another computer and tell me if it still happens.

**Comment by bhargavravat** [comment]
> Hi @bhargavravat, thank you for your interest in our project. There is something wrong in your Application GUI, a **File** button designated to located in the top left corner was missing.
> 
> Here is the right GUI:
> ![image](https://user-images.githubusercontent.com/30889332/55005278-4641ea80-500e-11e9-8c72-c39962d33850.png)
> 
> I do not know the reason why it is missing, we are under intensive discussion on this issue. You may try running this application on another computer and tell me if it still happens.

Hi @RykerLe : I tried running in different system as well , however the result is one and the same.

**Comment by thuyngch** [comment]
@bhargavravat Can you describe more about your system (OS version, Python version)?

**Comment by bhargavravat** [comment]
@AntiAegis : I am presently working on Ubuntu 16.04 LTS (64 bit ) system with Anaconda Environment which has Python 3.6.4 installed in it. Do I need to change python version ?

**Comment by thuyngch** [comment]
My system is Ubuntu 18.04 LTS (64bit), Python 3.6.5, and Pip.
Can you try to create a virtual environment using Pip and install packages with Pip?

**Comment by bhargavravat** [comment]
> My system is Ubuntu 18.04 LTS (64bit), Python 3.6.5, and Pip.
> Can you try to create a virtual environment using Pip and install packages with Pip?

@AntiAegis  : I have installed it with the same configuration mentioned by your side , still File tab is missing in it. 

![Screenshot from 2019-04-02 12-05-13](https://user-images.githubusercontent.com/11025174/55381119-d8cb1800-553f-11e9-81ed-4bfc2738bfeb.png)
