### ISSUE TITLE
Running python 2.alignment.py

### ISSUE THREAD

**Issue by yahyamhi** [AntiAegis/Face-Attendance-System#8]
$ python 2.alignment.py
Traceback (most recent call last):
  File "2.alignment.py", line 8, in <module>
    import lib.facenet as facenet
ModuleNotFoundError: No module named 'lib'

What do I do here? Thank You for the help

**Comment by vanshwason** [comment]
> $ python 2.alignment.py
> Traceback (most recent call last):
> File "2.alignment.py", line 8, in
> import lib.facenet as facenet
> ModuleNotFoundError: No module named 'lib'
> 
> What do I do here? Thank You for the help

hi, what was the solution to the problem?
